spring:
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}
#        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}